In [2]:
from pyspark.sql import SparkSession
from IPython.display import display


spark = SparkSession.builder.getOrCreate()

versions_df = spark.read.parquet("../data/processed/transform_versions.parquet")
display(versions_df.orderBy("generated_at_utc", ascending=False).toPandas())

,transform_version,generated_at_utc,target_width,target_height,resize_strategy,image_mode,image_format,partition_by,partitions,shuffle_partitions,rows_written,input_manifest_path,output_manifest_path,output_images_path
0,v1,2026-02-23T06:32:03.057549+00:00,224,224,keep_aspect_pad,L,PNG,"pathology,modality",16,16,3957,data/processed/manifest_bronze.parquet,data/processed/manifest_silver.parquet,data/processed/images_silver

In [4]:
split_versions_f = spark.read.parquet("../data/processed/split_versions.parquet")
display(versions_df.orderBy("generated_at_utc", ascending=False).toPandas().T)

                                                           0
transform_version                                         v1
generated_at_utc            2026-02-23T06:32:03.057549+00:00
target_width                                             224
target_height                                            224
resize_strategy                              keep_aspect_pad
image_mode                                                 L
image_format                                             PNG
partition_by                              pathology,modality
partitions                                                16
shuffle_partitions                                        16
rows_written                                            3957
input_manifest_path   data/processed/manifest_bronze.parquet
output_manifest_path  data/processed/manifest_silver.parquet
output_images_path              data/processed/images_silver